name: Springboot githubaction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: negotest-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

      #ignore에 담긴 application을 github가 추적을 못하므로 새롭게 생성
    - name: Make application.properties
      run: |
        mkdir ./src/main/resources
        cd ./src/main/resources
        touch ./src/main/resources/application.properties
        
        echo "${{ secrets.APPLICATION }}" | base64 --decode > ./src/main/resources/application.properties
      shell: bash

    - name: Make properties key.p8 file
      if: contains(github.ref, 'main')
      run: |
        mkdir -p ./src/main/resources/key
        cd ./src/main/resources/key

        touch ./AuthKey.p8

        echo "Copy APPLICATION"
        echo "${{ secrets.APPLICATION }}" > ./AuthKey.p8
      shell: bash

    #DB
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf-8'
        mysql database: 'manager'
        mysql user: 'kimjinoh_urim'
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

       # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

     # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./negotest.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./negotest.zip s3://$S3_BUCKET_NAME/

     # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CICD_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_SECRET_KEY }}
      run:
        aws deploy create-deployment
          --application-name negoTest
          --deployment-group-name nego-group 
          --file-exists-behavior OVERWRITE
          --s3-location bucket=negotest-deploy,bundleType=zip,key=negotest.zip
          --region ap-northeast-2